name: easy_firebase_notifications_handler
description: A comprehensive Flutter package for handling Firebase Cloud Messaging (FCM) notifications with intelligent caching, navigation, and multi-platform support (iOS, iPadOS, Android).
version: 1.0.1
homepage: https://github.com/GGFlutterdev/firebase_message_handler
repository: https://github.com/GGFlutterdev/firebase_message_handler
issue_tracker: https://github.com/GGFlutterdev/firebase_message_handler/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^16.1.1
  firebase_core: ^4.4.0
  overlay_support: ^2.1.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
